In [1]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[4.0466e+00, 4.5801e-41, 2.6353e-34],
        [3.0834e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [6.2121e+22, 1.8788e+31, 1.7220e+22],
        [2.3607e-09, 6.8316e-07, 1.3028e-11]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8731, 0.7013, 0.1488],
        [0.4568, 0.5910, 0.8000],
        [0.8141, 0.8209, 0.8866],
        [0.4480, 0.5458, 0.6110],
        [0.1910, 0.3429, 0.9694]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1819,  0.3442,  1.5546],
        [ 0.4182, -1.8140,  1.1393],
        [ 0.3504,  0.1534,  0.0985],
        [ 1.7304,  0.1737, -0.6403],
        [-0.4490, -1.6209,  0.5081]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [14]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.7740,  1.2595,  1.6522],
        [ 0.8652, -1.2697,  1.4039],
        [ 1.3373,  1.0231,  0.8144],
        [ 1.8872,  0.9641, -0.2655],
        [-0.2327, -1.3612,  1.0686]])


In [15]:
print(torch.add(x, y))

tensor([[ 1.7740,  1.2595,  1.6522],
        [ 0.8652, -1.2697,  1.4039],
        [ 1.3373,  1.0231,  0.8144],
        [ 1.8872,  0.9641, -0.2655],
        [-0.2327, -1.3612,  1.0686]])


In [16]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.7740,  1.2595,  1.6522],
        [ 0.8652, -1.2697,  1.4039],
        [ 1.3373,  1.0231,  0.8144],
        [ 1.8872,  0.9641, -0.2655],
        [-0.2327, -1.3612,  1.0686]])


In [18]:
print(x[:,1])

tensor([ 0.3442, -1.8140,  0.1534,  0.1737, -1.6209])


In [19]:
x

tensor([[ 1.1819,  0.3442,  1.5546],
        [ 0.4182, -1.8140,  1.1393],
        [ 0.3504,  0.1534,  0.0985],
        [ 1.7304,  0.1737, -0.6403],
        [-0.4490, -1.6209,  0.5081]])

In [20]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [21]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.1382])
-1.1382485628128052


In [22]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [23]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [24]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [25]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [26]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [27]:
import torch

In [28]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [29]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [30]:
print(y.grad_fn)

In [31]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [2]:
params = list(net.parameters())
print(len(params))
print(params[0].size())  # conv1's .weight

10
torch.Size([6, 1, 3, 3])
